/**
 * The one call the add-a-class-variable command makes to become undoable (issue #434).
 *
 * The same two-step handle and the same best-effort promise as the method and class
 * recorders — a capture that fails answers `undefined` and the add proceeds exactly as it
 * did before undo existed.
 *
 *   const recording = beginClassVarAdd(session, slot, accessorSlots);
 *   ... add the class variable, then generate its accessors ...
 *   recording?.commit('Add class variable Registry to Account');
 *
 * `commit` RE-READS the declaration and the accessor slots rather than being told what the
 * command did, because the accessors are generated by a separate call that skips any
 * selector the class already implements — the stone is the only thing that knows which of
 * them are actually new.
 */
import { ActiveSession } from '../sessionManager';
import { defaultQueryExecutorUsing } from '../browserQueries';
import { logInfo } from '../gciLog';
import { captureMethodSlots } from './queries/methodSlotQueries';
import { captureClassVar } from './queries/classVarQueries';
import { pushUndoEntry } from './undoStack';
import { ClassVarSlot, ClassVarState, MethodSlot, MethodSlotState, UndoEntry } from './undoTypes';

export interface ClassVarRecording {
  /** Whether the class already declared the name. The caller refuses the add in that case,
   *  so this is here for tests and for a caller that wants to check rather than assume. */
  readonly before: ClassVarState;
  commit(label: string): UndoEntry | undefined;
}

/**
 * Capture the declaration and the accessor slots as they stand, so the add about to happen
 * can be reversed.
 *
 * `accessorSlots` are the getter/setter the command will generate, or empty when the user
 * declined them. They are captured too, because an accessor that was already implemented is
 * skipped by the add and must be left alone by the undo.
 */
export function beginClassVarAdd(
  session: ActiveSession,
  slot: ClassVarSlot,
  accessorSlots: MethodSlot[],
): ClassVarRecording | undefined {
  // The executor lookup is inside the guard too: recording must never be the reason an
  // add fails.
  let execute;
  let before: ClassVarState;
  let accessorBefore: MethodSlotState[];
  try {
    execute = defaultQueryExecutorUsing(session);
    before = captureClassVar(execute, slot);
    accessorBefore = captureMethodSlots(execute, accessorSlots);
  } catch (e: unknown) {
    logInfo(
      `[undo] class-variable capture failed, add will not be undoable: ` +
        `${e instanceof Error ? e.message : String(e)}`,
    );
    return undefined;
  }
  if (accessorBefore.length !== accessorSlots.length) {
    logInfo('[undo] accessor capture answered the wrong number of states; add not undoable');
    return undefined;
  }

  return {
    before,
    commit(label: string): UndoEntry | undefined {
      let after: ClassVarState;
      let accessorAfter: MethodSlotState[];
      try {
        after = captureClassVar(execute, slot);
        accessorAfter = captureMethodSlots(execute, accessorSlots);
      } catch (e: unknown) {
        logInfo(
          `[undo] not recording "${label}": could not read the result ` +
            `(${e instanceof Error ? e.message : String(e)})`,
        );
        return undefined;
      }
      const accessorsChanged = accessorSlots.some(
        (_s, i) => accessorBefore[i]?.exists !== accessorAfter[i]?.exists,
      );
      if (after.defined === before.defined && !accessorsChanged) {
        logInfo(`[undo] not recording "${label}": the add changed nothing`);
        return undefined;
      }
      const entry = pushUndoEntry({
        kind: 'classVarEdit',
        sessionId: session.id,
        label,
        slot,
        before,
        after,
        accessorSlots,
        accessorBefore,
        accessorAfter,
      });
      logInfo(`[undo] recorded #${entry.id} "${label}" (${accessorSlots.length} accessor slot(s))`);
      return entry;
    },
  };
}
